#!/bin/sh
set -x

readonly switch=mistify0

echo "args: $# $@"
if [ -n "$1" ];then
        ip link set $1 down
	ovs-vsctl del-port $switch $1
else
        echo "Error: no interface specified"
        exit 1
fi
